version: "3.7"
services:
  app:
    container_name: app
    hostname: app
    ports:
    - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - DEBUG=true
      - POLL_INTERVAL=1000
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379

